# Generated by Django 6.0.1 on 2026-01-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0003_videovote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="dislikes",
            field=models.IntegerField(default=0),
        ),
    ]
