# Generated by Django 6.0.1 on 2026-01-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0004_alter_video_dislikes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="dislikes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
